### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by BinaryBrain** [DrawTable/GUI#1]
## Vital
- [x] Lancement du programme Java gérant la souris
- [ ] Amélioration de la précision des cliques
- [x] Clavier virtuel
- [x] Calibrage de la couleur
- [x] Gérer le cas où la caméra n'a pas bien détécté l'écran vert
- [x] Faire un joli packaging pour lancer le programme (dll, so, etc.)
## Important
- [x] Bouton pour changer l'épaisseur du trait plus accessible
- [x] Instructions pour l'utilisateur
- [x] Doxygenisation du code
- [ ] Bouton pour relancer la sélection de caméra et la calibration
- [x] Gérer le cas où l'utilisateur ne possède aucune webcam
## Cool
- [x] Éviter de demander à sauvegarder si le fichier n'a pas été modifié depuis la dernière sauvegarde (ou qu'il est vide)
- [x] Ajoutez automatiquement l'extension _.png_ aux images sauvegardées lorsque qu'elle n'est pas précisée
- [x] Sauvegardez/importez lors de l'appui sur la touche "Enter" du clavier virtuel
- [x] Sur le clavier virtuel, évitez d'écrire les lettre lorsque l'on appuie sur le bouton, puis on bouge la souris. Sinon, la lettre s'affiche à double.
- [ ] Faire une vraie synchro: https://github.com/DrawTable/GUI/blob/b74348ddb59cc7cf1983e50a0e26d62e54c9ad80/DrawTableGUI/camera/cameramanager.cpp#L72
- [x] Augmenter la largeur de la scrollbar dans les boîtes de dialogue.
- [x] Inverser ABC et 12# dans le clavier virtuel.
